# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogAddBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import library
import libgui
from PyQt5.QtWidgets import QMessageBox


class Ui_DialogBook(object):
    def setupUi(self, DialogBook, mainwindow):
        DialogBook.setObjectName("DialogBook")
        DialogBook.resize(584, 305)
        self.parent = mainwindow
        self.TitleField = QtWidgets.QLineEdit(DialogBook)
        self.TitleField.setGeometry(QtCore.QRect(110, 40, 471, 31))
        self.TitleField.setObjectName("TitleField")
        self.ConfirmBookButton = QtWidgets.QPushButton(DialogBook)
        self.ConfirmBookButton.setGeometry(QtCore.QRect(10, 240, 571, 25))
        self.ConfirmBookButton.setObjectName("ConfirmBookButton")
        self.label = QtWidgets.QLabel(DialogBook)
        self.label.setGeometry(QtCore.QRect(10, 46, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogBook)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 67, 31))
        self.label_2.setObjectName("label_2")
        self.AuthorField = QtWidgets.QLineEdit(DialogBook)
        self.AuthorField.setGeometry(QtCore.QRect(110, 80, 471, 31))
        self.AuthorField.setObjectName("AuthorField")
        self.YearField = QtWidgets.QLineEdit(DialogBook)
        self.YearField.setGeometry(QtCore.QRect(110, 120, 471, 31))
        self.YearField.setObjectName("YearField")
        self.comboBox = QtWidgets.QComboBox(DialogBook)
        self.comboBox.setGeometry(QtCore.QRect(110, 160, 471, 21))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(DialogBook)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 67, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogBook)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogBook)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 67, 31))
        self.label_5.setObjectName("label_5")
        self.TagField = QtWidgets.QLineEdit(DialogBook)
        self.TagField.setGeometry(QtCore.QRect(110, 190, 471, 31))
        self.TagField.setText("")
        self.TagField.setObjectName("TagField")
        self.CloseBookButton = QtWidgets.QPushButton(DialogBook)
        self.CloseBookButton.setGeometry(QtCore.QRect(10, 270, 571, 25))
        self.CloseBookButton.setObjectName("CloseBookButton")
        self.label_6 = QtWidgets.QLabel(DialogBook)
        self.label_6.setGeometry(QtCore.QRect(110, 10, 461, 17))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        genres = ["Other", "Adventure", "Romance", "Horror", "Crime",
                  "Classic", "History", "Comic book/Graphic novel",
                  "Crime/Mystery", "Fantasy", "Science Fiction",
                  "Horror", "Lifestyle", "Journalistic", "Self-Help",
                  "Theology", "Education", "Guides"]
        self.comboBox.addItems(genres)

        self.retranslateUi(DialogBook)
        QtCore.QMetaObject.connectSlotsByName(DialogBook)

        # functionality
        self.CloseBookButton.clicked.connect(DialogBook.close)
        self.ConfirmBookButton.clicked.connect(self.AddBook)

    def AddBook(self):
        title = self.TitleField.text()
        author = self.AuthorField.text()
        genre = self.comboBox.currentText()
        year = self.YearField.text()
        tags = self.TagField.text()
        s = library.openSession()
        library.addBook(s, title, author, year, genre, tags)
        s.close
        self.parent.refreshTables()
        QMessageBox.about(self.parent.centralwidget,
                          "Success", "Book added!")
        self.CloseBookButton.click()

    def retranslateUi(self, DialogBook):
        _translate = QtCore.QCoreApplication.translate
        DialogBook.setWindowTitle(_translate("DialogBook", "Add Client"))
        self.ConfirmBookButton.setText(_translate("DialogBook", "Confirm"))
        self.label.setText(_translate("DialogBook", "Title:"))
        self.label_2.setText(_translate("DialogBook", "Author:"))
        self.label_3.setText(_translate("DialogBook", "Genre:"))
        self.label_4.setText(_translate("DialogBook", "Year:"))
        self.label_5.setText(_translate("DialogBook", "Tags:"))
        self.TagField.setPlaceholderText(_translate(
            "DialogBook", "Input tags divided by \"#\""))
        self.CloseBookButton.setText(_translate("DialogBook", "Cancel"))
        self.label_6.setText(_translate("DialogBook", "Book details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogBook = QtWidgets.QDialog()
    ui = Ui_DialogBook()
    ui.setupUi(DialogBook)
    DialogBook.show()
    sys.exit(app.exec_())
